### ISSUE TITLE
Problem on "meta" object on /accounts/{creditCardAccountId}/bills/{billId}/transactions API

### ISSUE THREAD

**Issue by ranierimazili-gft** [OpenBanking-Brasil/draft-openapi#14]
The **meta** object is without totalPages and totalRecords attributes on success response body. I think it should be removed only on error responses.
P.S: The error is on 2.0 RC1 version.

**Comment by josehlxavier** [comment]
### Already fixed

Closing the issue. The funcionality was moved from the Accounts API to Credit Cards API and the "meta" object has both totalPages and totalRecords.
![image](https://github.com/OpenBanking-Brasil/draft-openapi/assets/118825553/eeb080d5-9b94-4d06-9c21-fa8ae3453c9f)
